name: 元智系统产品
url: http://products.microwise-system.com
mirror_url: http://products-mw-mirror.qiniudn.com
safe: true
lsi: false
markdown: redcarpet
highlighter: pygments
encoding: "utf-8"

gems:
  - jekyll-sitemap

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
