name: 元智系统产品
# url: http://products.microwise-system.com
url: http://localhost:4000
mirror_url: http://products-mw-mirror.qiniudn.com
safe: true
lsi: false
markdown: redcarpet
highlighter: pygments
encoding: "utf-8"

gems:
  - jekyll-sitemap
